export interface Issue {
     amcatId: number;
        dateOfDrive : any;
        venueOfDrive : string;
        studentName : string;
        gender : string;
        yearOfGraduation: number;
        collegeName: string;
        university: string;
        studentCourse: string;
        studentBranch: string;
        markTenth : number;
        markTwelve : number;
        collegeMarks: number;
        collegePercentage : number;
        studentAddress : string;
        studentMobile: number;
        additionalContactNumber : number;
        studentEmail : string;
        addtionalEmailId : string;
        collegeAddress: string;
        nameOfPlacementOfficer : string;
        numberOfPlacementOfficer : number;
        emailOfPlacementOfficer: string;
        preLearningLink: string;
        litmusbatch : string;
        litmusStatus : string;
        studentRemarks: string;
        studentAdditionalRemarks: string;
        createdTime: any;
        modifiedTime: any;
        joinYear : number;
        joinMonth : string;
        jobStatus : string;
        backgroundVerification : string;
        employeeId : number;
}
